import type { Metadata } from "next";
import { Raleway, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/footer";

const ralewayFont = Raleway({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-raleway",
});

const robotoMonoFont = Geist_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ralewayFont.variable} ${robotoMonoFont.variable}  antialiased`}
      >
        <main className="font-body">{children}</main>
      </body>
    </html>
  );
}
